FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    samtools tabix curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir pandas

COPY scripts/ ./scripts/
COPY Makefile .

ENTRYPOINT ["make"]
CMD ["data", "DATA_DIR=/data"]
