name: genome-browser
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - samtools
  - htslib
  - ncbi-datasets-cli
  - curl
  - unzip
  - pip
  - pip:
      - -r requirements.txt
